# Generated by Django 3.1.3 on 2020-11-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Microprocesador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('arquitectura', models.CharField(choices=[('X64', 'x64'), ('X86', 'x86')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaMemoriaRam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.IntegerField(help_text='En MB, ejemplo: 512, 1024, 2048', max_length=5)),
                ('fabricante', models.CharField(blank=True, max_length=10)),
                ('tipo', models.CharField(blank=True, help_text='Ejemplo: DDR2, DDR3, etc.', max_length=4)),
                ('velocidad', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
