# Generated by Django 3.1.3 on 2020-11-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_computadoras', '0002_auto_20201128_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoRigido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano', models.IntegerField(help_text='Tamaño en GB, ejemplo: 500, 1000, etc.')),
                ('fabricante', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Ubuntu 20.04 LTS', max_length=25)),
                ('arquitectura', models.CharField(choices=[('X64', 'x64'), ('X86', 'x86')], max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='tarjetamemoriaram',
            name='tamano',
            field=models.IntegerField(help_text='En MB, ejemplo: 512, 1024, 2048'),
        ),
    ]
