# Generated by Django 3.1.3 on 2020-11-28 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_computadoras', '0003_auto_20201128_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A_REVISAR', 'A revisar'), ('EN_PROGRESO', 'En progreso'), ('EN_PAUSA', 'En pausa'), ('LISTA', 'Lista')], max_length=12)),
                ('formato', models.CharField(choices=[('GABINETE', 'Gabinete'), ('NOTEBOOK', 'Notebook'), ('NETBOOK', 'Netbook'), ('ALL_IN_ONE', 'All in one')], max_length=12)),
                ('motherboard', models.CharField(blank=True, choices=[('FUNCIONA', 'Funciona'), ('NO_FUNCIONA', 'No funciona')], max_length=12)),
                ('audio', models.CharField(blank=True, choices=[('FUNCIONA', 'Funciona'), ('NO_FUNCIONA', 'No funciona')], max_length=12)),
                ('fuente', models.CharField(blank=True, choices=[('FUNCIONA', 'Funciona'), ('NO_FUNCIONA', 'No funciona')], max_length=12)),
                ('funcionamiento_red', models.CharField(blank=True, choices=[('FUNCIONA', 'Funciona'), ('NO_FUNCIONA', 'No funciona')], max_length=12)),
                ('cambio_pasta', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2)),
                ('disco', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventario_computadoras.discorigido')),
                ('memoria', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventario_computadoras.tarjetamemoriaram')),
                ('procesador', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventario_computadoras.microprocesador')),
                ('sistema_operativo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventario_computadoras.sistemaoperativo')),
            ],
        ),
    ]
