# Generated by Django 3.1.3 on 2020-12-14 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_computadoras', '0005_computadora_notas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computadora',
            options={'verbose_name_plural': 'Computadoras'},
        ),
        migrations.AlterModelOptions(
            name='discorigido',
            options={'verbose_name_plural': 'Discos Rígidos'},
        ),
        migrations.AlterModelOptions(
            name='microprocesador',
            options={'verbose_name_plural': 'Microprocesadores'},
        ),
        migrations.AlterModelOptions(
            name='sistemaoperativo',
            options={'verbose_name_plural': 'Sistemas operativos'},
        ),
        migrations.AlterModelOptions(
            name='tarjetamemoriaram',
            options={'verbose_name_plural': 'Tarjetas de Memoria RAM'},
        ),
    ]
